- name: Install and configure Fail2Ban
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    fail2ban_my_ip: "136.32.84.4" ##remove after testing
    fail2ban_bantime: 1800
    fail2ban_findtime: 600
    fail2ban_maxretry: 20
  tasks:
    - name: Install Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: yes
    - name: Configure Fail2Ban
      ansible.builtin.template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: Restart Fail2Ban
    - name: Create Sudo Fail2Ban Filter
      ansible.builtin.copy:
        dest: /etc/fail2ban/filter.d/sudo.conf
        content: |
          [Definition]
          failregex = ^sudo: .*: 3 incorrect password attempts.*$
          ignoreregex =
        mode: 0644
      notify: Restart Fail2Ban
  handlers:
    - name: Restart Fail2Ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
